name: contract-shield
region: nyc

services:
  # Backend API
  - name: backend
    type: web
    source_dir: /backend
    environment_slug: python
    run_command: uvicorn main:app --host 0.0.0.0 --port 8080
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /
    routes:
      - path: /api
    envs:
      - key: PORT
        value: "8080"

  # Frontend Web App
  - name: frontend
    type: web
    source_dir: /frontend
    environment_slug: node-js
    build_command: npm install && npm run build
    run_command: npm start
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: API_URL
        value: ${backend.PUBLIC_URL}
      - key: NEXT_PUBLIC_API_URL
        value: ${backend.PUBLIC_URL}
